# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('race', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Neither')], max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='reacted at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakTheStereoApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('listeners', models.ManyToManyField(through='breakTheStereoApp.Reaction', to='breakTheStereoApp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='reaction',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakTheStereoApp.Song'),
        ),
    ]
