# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakTheStereoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='chill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='cry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='dance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='rock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='romantic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='smile',
            field=models.IntegerField(default=0),
        ),
    ]
