# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakTheStereoApp', '0002_auto_20160724_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic_url',
            field=models.CharField(default='http://www.portraitprofessional.com/img/popin_2016.jpg', max_length=500),
        ),
    ]
